### ISSUE TITLE
Pandas dtype warning in pd.read_csv

### ISSUE THREAD

**Issue by BDannowitz** [plotly/dash-oil-and-gas-demo#4]
I cloned this repo, created a conda environment with the exact versions specified in the requirements file, but when I attempt to run `python app.py` to initiate this dashboard, I get the following error:

```
sys:1: DtypeWarning:

Columns (41,47) have mixed types. Specify dtype option on import or set low_memory=False.
```

If I change line 40 in `app.py` to the following, the error goes away:
```python
df = pd.read_csv('data/wellspublic.csv', low_memory=False)
```

It looks like this is acknowledged in the `explore.ipynb`, but not translated to `app.py`.

**Comment by Deejep** [comment]
Hi,
Same issue with me but it's related to the `points.pkl` file.

sys:1: DtypeWarning:

```
Columns (41,47) have mixed types. Specify dtype option on import or set low_memory=False.

Traceback (most recent call last):
  File "app.py", line 55, in <module>
    points = pickle.load(open("data/points.pkl", "rb"))
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto

```

**Comment by alishobeiri** [comment]
@Deejep Hi,

I think your issue is coming about because you are trying to use python2.7 to unpickle the `points.pkl` file. Since the file was pickled using a protocol specific to python3 so you need be using python3 to unpickle it.

**Comment by knageswara78** [comment]
I got a similar error and solved using the below code in Python 3.

import pandas as pd 
df = pd.read_csv('data.csv', index_col=None, na_values=['NA'],
                       sep=',',low_memory=False)
